/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empeado;

//import empeado.baseDeDatos.ConexionBD;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.util.ArrayList;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luponce
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    
    int edita;
    boolean nuevo;
    public FrmPrincipal() {
        edita=0;
        nuevo=true;
        initComponents();
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        Buscar.setEnabled(false);  
        this.setLocationRelativeTo(null);
//        JOptionPane.showMessageDialog(null, "apenas arranca "+edita);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrincipal = new javax.swing.JPanel();
        jLDatosEmpleado = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jLCargo = new javax.swing.JLabel();
        jCCargo = new javax.swing.JComboBox();
        jLFechaIngreso = new javax.swing.JLabel();
        jTFechaIngreso = new javax.swing.JTextField();
        jPBotones = new javax.swing.JPanel();
        jBEliminar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLDatosEmpleado.setText("Datos Empleado");

        jLCodigo.setText("Codigo:");

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoActionPerformed(evt);
            }
        });
        jTCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCodigoKeyTyped(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLApellido.setText("Apellido/s:");

        jLNombre.setText("Nombre/s:");

        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jLCargo.setText("Cargo:");

        jCCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR CARGO", "01-GERENTE", "02-EMPLEADO" }));
        jCCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCCargoItemStateChanged(evt);
            }
        });
        jCCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCargoActionPerformed(evt);
            }
        });

        jLFechaIngreso.setText("Fecha de Ingreso:");

        jTFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLDatosEmpleado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar))
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLApellido)
                            .addComponent(jLFechaIngreso)
                            .addComponent(jLNombre)
                            .addComponent(jLCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTApellido)
                            .addComponent(jTNombre)
                            .addComponent(jCCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFechaIngreso))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLDatosEmpleado)
                .addGap(18, 18, 18)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCargo)
                    .addComponent(jCCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaIngreso)
                    .addComponent(jTFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBotonesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed

    private void jTFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaIngresoActionPerformed

    private void jCCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCargoActionPerformed
        
    }//GEN-LAST:event_jCCargoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        nuevo=false;
//        JOptionPane.showMessageDialog(null, "ENTRANDO A MODIFICAR ");
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(false);
        Buscar.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBSalir.setEnabled(true);
        desactctrls(true);
    }//GEN-LAST:event_jBModificarActionPerformed
    
    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
            nuevo=true;
//            JOptionPane.showMessageDialog(null, "ENTRANDO A NUEVO");
            desactctrls(true);
            jBEliminar.setEnabled(false);
            jBNuevo.setEnabled(false);
            jBModificar.setEnabled(false);
            Buscar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGuardar.setEnabled(true);
            jBSalir.setEnabled(true);
            limpiar();
            desactctrls(true);
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(jTCodigo.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Debes ingresar un codigo para realizar la busqueda");
        }else{
            nuevo=false;  
            jBEliminar.setEnabled(true);
            jBModificar.setEnabled(true);
            jBNuevo.setEnabled(true);
            String cod = jTCodigo.getText();
            Persona per = GestorPersona.getInstancia().buscarPersona(cod);
            Empleado emp = GestorEmpleado.getInstancia().buscarEmpleado(cod);
            desactctrls(false);
            jTApellido.setText(per.getApellido());
            jTNombre.setText(per.getNombres());
            jCCargo.setSelectedIndex(Integer.parseInt(emp.getidCargo())-1);
            jTFechaIngreso.setText(emp.getFec_ing());
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        //this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoActionPerformed
      
    }//GEN-LAST:event_jTCodigoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
//        JOptionPane.showMessageDialog(null, "ENTRANDO A CANCELAR");
        desactctrls(true);
        jBEliminar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(false);
        Buscar.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBSalir.setEnabled(true);
        limpiar();
        desactctrls(true);
        nuevo=true;
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        boolean respuesta=validarTextboxes();
        if (respuesta){
        jBEliminar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(false);
        Buscar.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBSalir.setEnabled(true);
        
        String cod,nom,app,idcargo,fecha;
        cod=jTCodigo.getText();
        nom=jTNombre.getText();
        app=jTApellido.getText();
        idcargo=((String) jCCargo.getSelectedItem()).substring(0,2);
        fecha=jTFechaIngreso.getText();

        if(nuevo){//registro nuevo
                    Respuesta resp = GestorPersona.getInstancia().registrarPersona(cod,app,nom);
//                    if (resp.isEstado()) {
//                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
//                        //this.dispose();
//                    } else {
//                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
//                    }
                
                    Respuesta resp1 = GestorEmpleado.getInstancia().registrarEmpleado(cod,fecha,idcargo);
//                    if (resp1.isEstado()) {
//                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
//                        //this.dispose();
//                    } else {
//                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
//                    }
                    if(resp.isEstado()){
                        if(resp1.isEstado()){
                            JOptionPane.showMessageDialog(null,"Registro Exitoso");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Error en el registro");
                    }
        }else{//se modifica un registro existente
            Respuesta resp = GestorPersona.getInstancia().modificarPersona(cod,app,nom);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
            Respuesta resp1 = GestorEmpleado.getInstancia().modificarEmpleado(cod,fecha,idcargo);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
            
        }            
        
        nuevo=true;
        limpiar();
        desactctrls(true);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoKeyTyped
        Buscar.setEnabled(true);        
    }//GEN-LAST:event_jTCodigoKeyTyped

    private void jCCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCCargoItemStateChanged
        
    }//GEN-LAST:event_jCCargoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    private void desactctrls(boolean act){
        jTCodigo.setEnabled(act);
        jTApellido.setEnabled(act);
        jTNombre.setEnabled(act);
        jTFechaIngreso.setEnabled(act);
        jCCargo.setEnabled(act);
    }
    private void limpiar(){
        jTCodigo.setText("");
        jTApellido.setText("");
        jTNombre.setText("");
        jCCargo.setSelectedIndex(0);
        jTFechaIngreso.setText("");
    }
    
    private boolean validarTextboxes(){
        boolean respuesta=false;
        if(!jTCodigo.getText().equalsIgnoreCase("")){
            if(jTCodigo.getText().length()>4){
                JOptionPane.showMessageDialog(null, "El código debe contener un máximo de 4 números");
                return respuesta;
            }
            if(!jTApellido.getText().equalsIgnoreCase("")){
                if(!jTNombre.getText().equalsIgnoreCase("")){
                    if(jCCargo.getSelectedIndex()!=0){
                        if(!jTFechaIngreso.getText().equalsIgnoreCase(""))
                            respuesta=true;
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Los campos deben estar completos");
            respuesta=false;
        }
        return respuesta;
    }
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox jCCargo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDatosEmpleado;
    private javax.swing.JLabel jLFechaIngreso;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPrincipal;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTFechaIngreso;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables

}
