/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empeado;

import empeado.baseDeDatos.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luponce
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    int edita=1;
    public FrmPrincipal() {
         
        initComponents();
        jBEliminar.setEnabled(false);
        jBModificar.setEnabled(false);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrincipal = new javax.swing.JPanel();
        jLDatosEmpleado = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jLCargo = new javax.swing.JLabel();
        jCCargo = new javax.swing.JComboBox();
        jLFechaIngreso = new javax.swing.JLabel();
        jTFechaIngreso = new javax.swing.JTextField();
        jPBotones = new javax.swing.JPanel();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLDatosEmpleado.setText("Datos Empleado");

        jLCodigo.setText("Codigo:");

        jTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLApellido.setText("Apellido/s:");

        jLNombre.setText("Nombre/s:");

        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jLCargo.setText("Cargo:");

        jCCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01-GERENTE", "02-EMPLEADO" }));
        jCCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCargoActionPerformed(evt);
            }
        });

        jLFechaIngreso.setText("Fecha de Ingreso:");

        jTFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLDatosEmpleado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar))
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLApellido)
                            .addComponent(jLFechaIngreso)
                            .addComponent(jLNombre)
                            .addComponent(jLCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCCargo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLDatosEmpleado)
                .addGap(18, 18, 18)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCargo)
                    .addComponent(jCCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaIngreso)
                    .addComponent(jTFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jBModificar)
                .addGap(33, 33, 33)
                .addComponent(jBEliminar)
                .addGap(34, 34, 34)
                .addComponent(jBSalir)
                .addContainerGap())
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar)
                    .addComponent(jBModificar)
                    .addComponent(jBNuevo)
                    .addComponent(jBSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed

    private void jTFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaIngresoActionPerformed

    private void jCCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCargoActionPerformed
        
    }//GEN-LAST:event_jCCargoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        int edita=1;
        
        if (jBModificar.getText().equals("Modificar")) {
            jBNuevo.setText("Grabar");
            jBModificar.setText("Cancelar");
            edita=1;
            
            desactctrls(true);
            jBEliminar.setEnabled(false) ;
            Buscar.setEnabled(false);
        } else if(jBModificar.getText().equals("Cancelar")) {
            jBNuevo.setText("Nuevo");
            jBModificar.setText("Modificar");
            limpiar();
            jBEliminar.setEnabled(false);
            Buscar.setEnabled(true);
            desactctrls(true);
        }

    }//GEN-LAST:event_jBModificarActionPerformed
    
    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        
        String cod,nom,app,idcargo,fecha;
        cod=jTCodigo.getText();
        nom=jTNombre.getText();
        app=jTApellido.getText();
        idcargo=((String) jCCargo.getSelectedItem()).substring(0,2);
        fecha=jTFechaIngreso.getText();
        if (jBNuevo.getText().equals("Nuevo")) {
            jBNuevo.setText("Grabar");
            edita=0;
            desactctrls(true);
            jBEliminar.setEnabled(false);
            Buscar.setEnabled(false);
            limpiar();
        } else if(jBNuevo.getText().equals("Grabar")) {
            JOptionPane.showMessageDialog(null, edita);
            
                jBNuevo.setText("Nuevo");
                jBModificar.setText("Modificar");
                if (edita==0){
                    Respuesta resp = GestorPersona.getInstancia().registrarPersona(cod,app,nom);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                
                    Respuesta resp1 = GestorEmpleado.getInstancia().registrarEmpleado(cod,fecha,idcargo);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else if (edita==1){
                    JOptionPane.showMessageDialog(null, "modif");
                    Respuesta resp = GestorPersona.getInstancia().modificarPersona(cod,app,nom);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                
                    Respuesta resp1 = GestorEmpleado.getInstancia().modificarEmpleado(cod,fecha,idcargo);
                    if (resp.isEstado()) {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Info", JOptionPane.INFORMATION_MESSAGE);
                        //this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, resp1.getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                        
                }
                desactctrls(true);
                limpiar();
                jBEliminar.setEnabled(false);
                Buscar.setEnabled(true);
           
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        jBEliminar.setEnabled(true);
        jBModificar.setEnabled(true);
        String cod = jTCodigo.getText();
        Persona per = GestorPersona.getInstancia().buscarPersona(cod);
        Empleado emp = GestorEmpleado.getInstancia().buscarEmpleado(cod);
        desactctrls(false);
        //JOptionPane.showMessageDialog(null, emp.toString());
        jTApellido.setText(per.getApellido());
        jTNombre.setText(per.getNombres());
        jCCargo.setSelectedIndex(Integer.parseInt(emp.getidCargo())-1);
        jTFechaIngreso.setText(emp.getFec_ing());
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        //this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoActionPerformed
      
    }//GEN-LAST:event_jTCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
      private void desactctrls(boolean act){
        jTCodigo.setEnabled(act);
        jTApellido.setEnabled(act);
        jTNombre.setEnabled(act);
        jTFechaIngreso.setEnabled(act);
        jCCargo.setEnabled(act);
    }
    private void limpiar(){
        jTCodigo.setText("");
        jTApellido.setText("");
        jTNombre.setText("");
        jCCargo.setSelectedIndex(0);
        jTFechaIngreso.setText("");
    }
    
    
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox jCCargo;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDatosEmpleado;
    private javax.swing.JLabel jLFechaIngreso;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPrincipal;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTFechaIngreso;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables

}
